### ISSUE TITLE
ModuleNotFoundError: No module named 'progress'

### ISSUE THREAD

**Issue by Thaone73** [AdamSpannbauer/python_video_stab#18] opened 2018-07-28 04:29 UTC
I get this error when I use `python -m pip install vidstab`.
```
...Collecting progress (from vidstab)
  Using cached https://files.pythonhosted.org/packages/e9/ff/7871f3736dc6707435b2a2f217c46b5a5bc6ea7e0a9a443cd69146a1afd1/progress-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bernard\AppData\Local\Temp\pip-install-w0qzry3z\progress\setup.py", line 5, in <module>
        import progress
    ModuleNotFoundError: No module named 'progress'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Bernard\AppData\Local\Temp\pip-install-w0qzry3z\progress\
```

**Comment by AdamSpannbauer** [comment] 2018-07-28 11:35
Looks like the issue is coming up when the process is trying to install the [`progress`](https://pypi.org/project/progress/) package.  Try installing the package by itself by running `pip install progress` from the command line.  If that fails try running running `pip install --upgrade --force-reinstall progress`.

**Comment by Thaone73** [comment] 2018-07-28 13:01
Thanks.
It does not work:
C:\WinPython-64bit-3.6.0.1Qt5\python-3.6.0.amd64>python -m pip install progress
Collecting progress
  Using cached https://files.pythonhosted.org/packages/e9/ff/7871f3736dc6707435b2a2f217c46b5a5bc6ea7e0a9a443cd69146a1afd1/progress-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bernard\AppData\Local\Temp\pip-install-ubar11ny\progress\setup.py", line 5, in <module>
        import progress
    ModuleNotFoundError: No module named 'progress'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Bernard\AppData\Local\Temp\pip-install-ubar11ny\progress\

C:\WinPython-64bit-3.6.0.1Qt5\python-3.6.0.amd64>python -m pip install --upgrade --force-reinstall progress
Collecting progress
  Using cached https://files.pythonhosted.org/packages/e9/ff/7871f3736dc6707435b2a2f217c46b5a5bc6ea7e0a9a443cd69146a1afd1/progress-1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Bernard\AppData\Local\Temp\pip-install-sqcwr7lr\progress\setup.py", line 5, in <module>
        import progress
    ModuleNotFoundError: No module named 'progress'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Bernard\AppData\Local\Temp\pip-install-sqcwr7lr\progress\

**Comment by AdamSpannbauer** [comment] 2018-07-30 16:30
Are you able to install any packages using `pip`?

However, since this issue is around an error installing the `progress` package I will be closing the issue here.  If you are still having the problem I would suggest posting on StackOverflow or opening an issue within the [`progress github repo`](https://github.com/verigak/progress).

**Closed by AdamSpannbauer** 2018-07-30 16:30 UTC

**Comment by Thaone73** [comment] 2018-07-31 00:15
Yes, no problem in installing other packages with pip.
I understand it is probably a separate issue. Thank you for your advises~

**Comment by gzcy13** [comment] 2021-07-08 12:09
you maybe could try :
pip3 install progress

**Comment by liam274** [comment] 2021-12-10 02:12
I can't use it

**Comment by liam274** [comment] 2021-12-10 02:13
It says:
C:\Users\>pip3 install progress
Requirement already satisfied: progress in c:\programdata\anaconda3\lib\site-packages (1.6)
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\programdata\anaconda3\python.exe -m pip install --upgrade pip' command.

**Comment by liam274** [comment] 2021-12-10 02:14
But at python:
Traceback (most recent call last):
  File "C:\Users\classroom\Desktop\test.py", line 2, in <module>
    from progress.bar import Bar
ModuleNotFoundError: No module named 'progress'

**Comment by AdamSpannbauer** [comment] 2021-12-10 14:38
@liam274 my guess is that the installation of python you're using is not looking in the same place that you're installing.  Try running:

```python
import sys
print(sys.path)
```

Your `pip` output says that it installed to: `c:\programdata\anaconda3\lib\site-packages`.  If you don't see that path in the `sys.path` list then you are not installing in a place that your python session is 👀 ing
